### ISSUE TITLE
Unreviewed changes of regular trips PR

### ISSUE THREAD

**Issue by pierrecamilleri** [fabmob/standard-covoiturage#16]
I report unreviewed changes of the PR #11, so that they can be discussed (and if necessarily patched). The PR has been merged in order to have a consolidated branch.

These changes concern: 
- The `minDepartureDate` parameter for regular trips search
- The `departureWeekdays` parameter for regular trips search
- A `webUrl` parameter for `Trip`s

Here is [the link](https://github.com/fabmob/standard-covoiturage/pull/11/files/67f3e59d0a176e6416de8bb609b6544727970534..f0edc0fc398d4464c60f4a0b045f6cf7722ab967) to check the mentioned changes.

**Comment by adelcasse** [comment]
OK for me

**Comment by pierrecamilleri** [comment]
I think we can close this issue. Feel free to reopen it if needed.
