### ISSUE TITLE
the "JourneySchedules" field starts with a capital letter 

### ISSUE THREAD

**Issue by Fatimaezzahra100** [fabmob/standard-covoiturage#37]
https://github.com/fabmob/standard-covoiturage/blob/ffe767eb86bc31cfa10e416017afa56b92a66faa/standard-covoiturage_openapi.yaml#L668

Hello !

I find that the field "JourneySchedules" starts with an uppercase letter for both end-point : /driver-regular-trips && /passenger-regular-trips.  It is the only field among all the fields which starts with a capital letter.

![image](https://user-images.githubusercontent.com/62389489/178423273-68f175de-624e-44a3-b734-1e106eae0cae.png)

I wonder if it is an error or is the field is written like that in the standard-covoiturage ?

Thank you.

**Comment by pierrecamilleri** [comment]
Thank you, it was indeed a typo and it is now fixed.
